development: &default
  adapter: postgresql
  host: localhost
  database: order_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: static_test

production:
  adapter: postgresql
  database: order_production
  pool: 5
  timeout: 5000
